### ISSUE TITLE
uclogic driver non-functional after commit "Extract report descriptors to a module"

### ISSUE THREAD

**Issue by makomk** [DIGImend/digimend-kernel-drivers#112]
Hi. At least for me when building against Linux 4.14.13, commit e656ddecc526d798097b7ecf15a0a1c0cb0dc0d6 "uclogic: Extract report descriptors to a module" renders the uclogic driver completely non-functional - the kernel doesn't even see it as a HID driver when the module is loaded. The problem appears to be that the main file hid-uclogic.c has the same name as the kernel module, meaning that it compiles to an object file hid-uclogic.o. According to the kbuild docs, the module build process involves combining all of the object files for the module into a single object file that's also called hid-uclogic.o. The result of this name clash for me is that none of the code in hid-uclogic.c actually gets compiled into the kernel module, so it isn't even registered with the HID layer when loaded and effectively does nothing. (I've checked the symbols in the resulting module file and everything from hid-uclogic.c is simply missing.)

Renaming hid-uclogic.c to something that doesn't clash with the module name seems to make the driver work correctly again. As far as I can tell, it doesn't seem to be possible to give a C source file the same name as the kernel module unless it's the only source file making up that module.

**Comment by spbnick** [comment]
Thank you very much for a thorough investigation, report, and explanations, @makomk! My fault, I didn't test the driver properly before pushing. Fixed now.
