### ISSUE TITLE
Incompatible pointer type (Manjaro 17.1.6)

### ISSUE THREAD

**Issue by zapado-ozero** [DIGImend/digimend-kernel-drivers#127]
Hi,
I tried installing the driver and got an error running `make`
The message I got is:
`/home/zapado/Downloads/digimend/digimend-kernel-drivers-6/hid-uclogic.c:1101:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .input_configured = uclogic_input_configured,

 ^~~~~~~~~~~~~~~~~~~~~~~~
`
Thank you in advance

**Comment by spbnick** [comment]
@zapado-ozero, this is fixed in [v7 release](https://github.com/DIGImend/digimend-kernel-drivers/releases/tag/v7).
