### ISSUE TITLE
Gaomon M106K frame button registered as mouse

### ISSUE THREAD

**Issue by Pixdigit** [DIGImend/digimend-kernel-drivers#153]
The frame buttons on the Gaomon M106K are mapped as mouse buttons. As most software does not allow mapping mouse buttons to shortcuts it would be useful if they were mapped as keyboard buttons.

**Comment by spbnick** [comment]
Thank you for the report, @Pixdigit. This is done on purpose, for compatibility with the Wacom driver. Take a look at the [Configuration section](https://github.com/DIGImend/digimend-kernel-drivers#configuration) in README.md. It describes how to configure the Wacom driver to handle your tablet and it gives a hint on how to assign shortcuts to these buttons.

**Comment by Pixdigit** [comment]
…so the wacom driver augments the digimend drivers? Because my tablet isn't compatible with wacom per-se

**Comment by spbnick** [comment]
@Pixdigit, compatibility can be ensured at any level, and in this case the kernel drivers make your tablet look sufficiently like a Wacom tablet to the X.org driver. Give it a go :)

**Comment by Pixdigit** [comment]
Ok, thank you very much. I'll get back to you once I tried it.

**Comment by Pixdigit** [comment]
Works now.
(For future reference it would be nice to have a short sentence explaining why you need the extra step of using the wacom driver to avoid confusion)

**Comment by spbnick** [comment]
@Pixdigit, I think I wrote something in the configuration section, but I'd be glad to merge a PR improving that :)
