### ISSUE TITLE
Drivers and Secure Boot

### ISSUE THREAD

**Issue by franzulu** [DIGImend/digimend-kernel-drivers#155]
Hi. Is it possible to use the drivers without disabling Secure Boot?

Thanks

**Comment by spbnick** [comment]
I've never setup or used secure boot myself, only read about it, but I think this boils down to just signing the kernel modules. Look for a documentation on that for your distribution. Here's some Fedora documentation for example: https://docs-old.fedoraproject.org/en-US/Fedora/23/html/System_Administrators_Guide/sect-signing-kernel-modules-for-secure-boot.html
