### ISSUE TITLE
I have problem with driver on H580

### ISSUE THREAD

**Issue by 3dstar** [DIGImend/digimend-kernel-drivers#16]
Hi.
Firstly my device work, but work very slow pan in gimp and mari.

I am install new driver, reboot machine, but device dont work correctly.

I dont remove driver 'make uninstall' in current folder  
http://joxi.ru/xAe0OqBSxkbe2y

please help me

**Comment by spbnick** [comment]
I believe this problem was handled on the maillist and via personal mail.
