### ISSUE TITLE
Install Version 8

### ISSUE THREAD

**Issue by YiffFurryberg** [DIGImend/digimend-kernel-drivers#161]
I have a huion 640p and the website says it is available in version 8 and above, but I can only find the installation for version 7.

**Comment by sceext2** [comment]
You can compile it from the master branch.

<https://github.com/DIGImend/digimend-kernel-drivers/blob/master/hid-uclogic-core.c#L411>

**Comment by YiffFurryberg** [comment]
How would I go about doing that?

**Comment by ThePreviousOne** [comment]
[digimend-dkms_8_all.deb...zip](https://github.com/DIGImend/digimend-kernel-drivers/files/2112118/digimend-dkms_8_all.deb.zip)

rename from zip
