### ISSUE TITLE
Huion New 1060PLUS

### ISSUE THREAD

**Issue by LittleFranky** [DIGImend/digimend-kernel-drivers#174]
i got the huion new 1060 plus basically to work. thanks for your work! but I experience one bug. holding two buttons on the pen doesn't work. it registers as just one button. can you fix that?

**Comment by spbnick** [comment]
Hi @LittleFranky, unfortunately it's how these particular tablets work, they don't report both buttons as pressed, there's nothing the Linux driver can do about it, the tablet's firmware needs to be updated, which likely means you would need to buy a new tablet. Please raise the issue with Huion. It will go easier if you provide Windows testing results.

**Comment by LittleFranky** [comment]
Thank you for your reply. I'll write Huion then and hope that they fix it in a new generation. Can you recommend a similar priced and quality tablet that doesn't have this bug?

**Comment by spbnick** [comment]
@LittleFranky, unfortunately not, I was focusing on Huion tablets recently, and they all are behaving similarly.
