### ISSUE TITLE
Huion H610PRO strokes end registering when I move pen away from tablet.

### ISSUE THREAD

**Issue by saidwho12** [DIGImend/digimend-kernel-drivers#194]
Is there a way to configure this tablet to end registering stylus press when the pen is no longer pressed against the surface? Right now it only registers a "release" it seems only when pen is no longer even near the surface. If you need more info please request it.

**Comment by saidwho12** [comment]
Sorry actually I found out this is hardware issue. My pen is just malfunctioning because I let my brother use it once and he bashed it into the tablet too hard and broke something inside.

**Comment by spbnick** [comment]
Sad to hear, hope you find a replacement!

**Comment by saidwho12** [comment]
thanks, I will have to now :(
