### ISSUE TITLE
Huion 1060 Plus not working

### ISSUE THREAD

**Issue by ManuUE** [DIGImend/digimend-kernel-drivers#224]
Hi,

i am a simple Linux User and my Huion Tablet not works. DIGImend is installed. Do I have to do something else?

System: Linux MInt Debian Edition

**Comment by ALTracer** [comment]
Did you do `make dkms_install` ? The upstream kernel might have a hid_uclogic driver with same version as this repository. Try other methods: github deb package, github tar dkms from source. If DKMS throws you a `not newer`, say `sudo dkms remove -m digimend/9 --all && sudo dkms install --force -m digimend/9`

**Comment by spbnick** [comment]
Closing this issue, as there's no response from the reporter. @ManuUE, please reopen, if you still need help.
