### ISSUE TITLE
Xinput coordinate transform matrix.

### ISSUE THREAD

**Issue by Cpt-Ktw** [DIGImend/digimend-kernel-drivers#226]
I find it extremely confusing. 
What should my transform matrix look like if I have :

1. Dual monitor setup one 1920x1080 and another 3840x2160(i need to be active)

2. 16/10 tablet active area while the monitor is 16/9

**Comment by spbnick** [comment]
This is an involved case, and unfortunately I don't have enough time to remember how the math works and help you. However, if you search the web for something like "calculate coordinate transformation matrix for xinput" or such, you should be able to find some articles, answers, scripts, and even spreadsheets to help you figure it out.

**Comment by spbnick** [comment]
Closing, as there's no further communication from the reporter. @Cpt-Ktw, please reopen, if you still need help.
