### ISSUE TITLE
After installing digimend-dkms_9_all.deb on Ubuntu 16.0.4 xorg-server not start

### ISSUE THREAD

**Issue by sagaru-es** [DIGImend/digimend-kernel-drivers#250]
Hi guys,

After installing digimend-dkms_9_all.deb on my Unbuntu 16.0.4 and Lubuntu 16.0.5 the xorg-server not start.

The system givs me a parse error : 

> "NoMatchProduct" is not a valid keyword in this section.

In order to solve it I have to comment line 18 of /usr/share/X11/xorg.conf.d/50-digimend.conf file:

` #	NoMatchProduct "MousePen"`

After comment this line, my Huion H430P starts to work but I do not know how to configure the buttons or the pressure when drawing.

Regards.

**Comment by spbnick** [comment]
Thank you for the report, @sagaru-es. Yes that's an issue, I forgot to fix before making the release. You can use [the latest development version](https://github.com/DIGImend/digimend-kernel-drivers/archive/master.zip) instead, where this is fixed.
