### ISSUE TITLE
Driver interrupt startx

### ISSUE THREAD

**Issue by snnooze** [DIGImend/digimend-kernel-drivers#262]
Hello,
I've just installed the drivers for my huion Q11K on a slackware 14.2
The pen works with pressure but the driver generate an error when I type startx
The problem come from (I think) the line 18 of the file `/usr/share/X11/xorg.conf.d/50-digimend.conf`
If I comment that line `NoMatchProduct "MousePen"` , all works fine

**Comment by spbnick** [comment]
Hi Fabrice,
Yes, sorry about that. That line would only work on newer X.org versions. The problem was fixed in the [latest development version](https://github.com/DIGImend/digimend-kernel-drivers/archive/master.zip). You could use that or just have the line removed.
