### ISSUE TITLE
Not working on the Huion H320M

### ISSUE THREAD

**Issue by StellarisStudio** [DIGImend/digimend-kernel-drivers#333]
Christmas Fail - Fucking Huion
I'm so pissed off.... I buy this tablet cause it was written compatible with Linux... But not !!!
And I try to follow everything, but at the end, it doesn't work !!!

The thing strange is that some button work, but not all and not the pen...

(I use the  5.0.0-37-generic kernel)

**Comment by fontenele** [comment]
not working here too

**Comment by holic-cl** [comment]
Not working yet
