### ISSUE TITLE
Gaomon s620 ubuntu

### ISSUE THREAD

**Issue by de1uxe** [DIGImend/digimend-kernel-drivers#376]
Is this tablet supported on ubuntu 18.04? I want to use it for osu!

**Comment by DavidHusicka** [comment]
I use Gaomon S620 for osu on my Linux system and it works. The care of this tablet is taken by one of Huion drivers in this repo. This tablet is reported to the kernel as a Huion tablet.

**Comment by spbnick** [comment]
Closing, since the tablet is supported, and there's no response from the reporter.

**Comment by attila-i-szabo** [comment]
> I use Gaomon S620 for osu on my Linux system and it works. The care of this tablet is taken by one of Huion drivers in this repo. This tablet is reported to the kernel as a Huion tablet.

Could you give some instructions? I installed the repo from the .deb file, plugged in the tablet, but it doesn't work. I get a USB device ID 256c:006d without any description, and it isn't recognised by xinput or anything else...

**Comment by bigbigmdm** [comment]
Please see my repository in the [https://github.com/bigbigmdm/GAOMON-S620-in-LINUX](github)
