### ISSUE TITLE
Huion H640P - wrong PID name

### ISSUE THREAD

**Issue by canorve** [DIGImend/digimend-kernel-drivers#379]
I just bought a HUION H640P for my Dell laptop with elementary OS. 

The driver didn't work at first, but following your tutorial 
"How to locate a failure", I notice that the PID is wrong. Your tablet driver support says that
for my tablet is  256c:006e, instead of 256c:006d after checking with "lsusb" and "usbhid-dump".

So, I changed line 9 in **xorg.conf** file to  
`MatchUSBID "5543:006e|256c:006d"`
and the tablet worked

By the way, the issue is resolved, but I wanted you guys to notice this problem.

**Comment by spbnick** [comment]
Thank you for the report, Chris. The 6d PID is used by newer models, and the latest development version of the drivers should know about it. Which version were you using?

**Comment by canorve** [comment]
I assume it is the last one:  Version 9

**Comment by chexbox** [comment]
Thank You! On Ubuntu (Digimend v9) It didn't have a section for the Huion H640P at all. I got the PID set, and it seems to be working. My tablet, however doesn't seem to report the x-coordinate on about 1/2 the tablet.

**Comment by ruhsontorugut** [comment]
> Thank You! On Ubuntu (Digimend v9) It didn't have a section for the Huion H640P at all. I got the PID set, and it seems to be working. My tablet, however doesn't seem to report the x-coordinate on about 1/2 the tablet.
I don't really understand English
But maybe your tablet on phone mode so only half of tablet register your input correctly
Try press button 1 + button 5 to enter computer mode

**Comment by JoseKling** [comment]
I have the same problem. But I don't know how to change this configuration.
My OS is Manjaro KDE.
Thanks
