### ISSUE TITLE
Mainlining

### ISSUE THREAD

**Issue by ticotaco72** [DIGImend/digimend-kernel-drivers#421]
Hello,
Why Digimend isn't mainlained in kernel, and/or any other component that it attaches to?

**Comment by Korvox** [comment]
It is mainlined, releases are just staggered. Ex [hid-uclogic.c](https://github.com/DIGImend/digimend-kernel-drivers/blob/master/hid-uclogic-core.c) can be found [upstream here](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-uclogic-core.c). All the files end up in drivers/hid/.

Linux drivers are developed this way fairly universally - you have an out of tree project implementing changes that gets regularly merged in one bulk patchset. That way the mailing list isn't inundated with every single commit into every single driver.
