### ISSUE TITLE
Compiling in ubuntu 16.04

### ISSUE THREAD

**Issue by carlesoriol** [DIGImend/digimend-kernel-drivers#46]
Hi I'm compiling in ubuntu 16.04  and I got several SSL errors on sudo make install.

What should I do? Thanks for your huge work.

Carles

make -C /lib/modules/4.4.0-38-generic/build SUBDIRS=/home/carles/Baixades/digimend-kernel-drivers-6 modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-38-generic'
  INSTALL /home/carles/Baixades/digimend-kernel-drivers-6/hid-kye.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL /home/carles/Baixades/digimend-kernel-drivers-6/hid-polostar.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  INSTALL /home/carles/Baixades/digimend-kernel-drivers-6/hid-uclogic.ko
At main.c:222:
- SSL error:02001002:system library:fopen:No such file or directory: bss_file.c:175
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: bss_file.c:178
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.4.0-38-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-38-generic'
install -D -m 0644 digimend.conf /etc/depmod.d/digimend.conf
depmod -a
install hid-rebind /sbin/hid-rebind
install -m 0644 90-hid-rebind.rules /lib/udev/rules.d/90-hid-rebind.rules
udevadm control --reload

**Comment by spbnick** [comment]
I suspect that it simply fails to sign the driver. If the install otherwise completes normally, then it shouldn't be a problem.
