### ISSUE TITLE
Huion NEW 1060Plus flips hover with click

### ISSUE THREAD

**Issue by drskoolie** [DIGImend/digimend-kernel-drivers#494]
Just installed the latest version from source manually. And it seems to switch the keys, here is description of the problem:

1. When the pen is hovering or touching the tablet, it registers it as if I'm holding the left click mouse down.
2. When I press the button on the side, it registers it stops clicking the mouse down.

So to use it, I will first hold down the button on the side to move the mouse around then let go when I want to click on something. I would like for it to do this:

1. When hovering, move mouse around
2. When touching the tablet, left click down
3. When pressing the button on the side, right click down.

Not too Linux savvy, how would I go about doing this. Thanks.

**Comment by a-elhag** [comment]
Here is the diagnostics asked for here: http://digimend.github.io/support/howto/trbl/diagnostics/.

[descriptors.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5706899/descriptors.txt)
[hid_report_descriptors.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5706900/hid_report_descriptors.txt)
[pen_coords.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5706901/pen_coords.txt)
[pen_pressure.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/5706902/pen_pressure.txt)

And this is my system information:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
