### ISSUE TITLE
Ugee hk1060pro Supported?

### ISSUE THREAD

**Issue by keranapy** [DIGImend/digimend-kernel-drivers#497]
Hello, I was just wondering if the UGEE HK1060 pro is currently supported.

**Comment by nic3-14159** [comment]
Hello! As far as I can tell, that tablet is not currently supported. Do you happen to have that tablet? If so, would you be able to post diagnostics as outlined on [this page](https://digimend.github.io/support/howto/trbl/diagnostics/)? That would be useful to anyone working on adding support for that tablet.

**Comment by keranapy** [comment]
> Hello! As far as I can tell, that tablet is not currently supported. Do you happen to have that tablet? If so, would you be able to post diagnostics as outlined on [this page](https://digimend.github.io/support/howto/trbl/diagnostics/)? That would be useful to anyone working on adding support for that tablet.


Ok thanks for answering I will do it, I will try
