### ISSUE TITLE
Question: Is pressure sensitivity solved for Huion H610 on Linux?

### ISSUE THREAD

**Issue by Moini** [DIGImend/digimend-kernel-drivers#5]
I didn't know where to ask, sorry for the 'issue' :-(

And another question: Do you, by chance, know what are the differences between H610, H610Pro and H610N ? Which of those have you been able to test with the driver on Linux?

(I'm not sure vendors know the difference themselves, as I often see 'pro' and "(without suffix)" mixed in shops and info on the huion website is - ehem - scarce...)

Thank you very much!

**Comment by spillz** [comment]
Hi, I am also having trouble with pressure sensitivity on the Huion H610 running on Ubuntu 14.04 using this driver:

https://github.com/DIGImend/digimend-kernel-drivers/releases/tag/v5

Sensitivity doesn't appear to work at all. I have the driver installed and here's a snippet from my 52-wacom.conf:

   Section "InputClass"
   	Identifier "Wacom class"
   	MatchProduct "Wacom|WACOM|Hanwang|PTK-540WL|ISD-V4|HUION PenTablet"
   	MatchDevicePath "/dev/input/event*"
   	Driver "wacom"
   EndSection

I've tried tweaking settings in Gimp/Inkscape to no avail. Is there something obvious I am missing?

**Comment by spbnick** [comment]
Could you please post the output of "evtest" for your tablet pen device (the one which responds to pen movements), while you do a stroke with the pen? This way we'll be able to see if the kernel reports pressure, or not. Thank you.

**Comment by spillz** [comment]
Ugh, sorry for wasting your time. it looks like a reboot did the trick. But only with Gimp. I'm using Inkscape 0.91 and for some reason it is reporting four devices instead of the three that Gimp reports. I have tried various combinations of Screen/Disabled and none of them will give me a pressure sensitive calligraphic stroke :/

Here's the [inkscape input devices screenshot on imgur](http://imgur.com/mOaY4bi)

**Comment by spillz** [comment]
Amazingly, removing overlay-scrollbars is the fix for the Inkscape issue: https://bugs.launchpad.net/ubuntu/+source/inkscape/+bug/790130
