### ISSUE TITLE
Is Gaomon M6 supported in Ubuntu 20.04??

### ISSUE THREAD

**Issue by nukawa** [DIGImend/digimend-kernel-drivers#562]
Recently I got a Gaomon M6, it could be detected as Huion tablet (256c:0064) in lsusb.
I did not find it in the list of supported tablets but this one looks like Gaomon M10K and Huion HS610.
Although HS610 seems not supported either, I also tried another method with "digimend-kernel-drivers-support_huion_hs610", but still fail.
Does anyone out there have this M6 working in Ubuntu??? Thanks a lot.

**Comment by nukawa** [comment]
Dear sir, 
I also attached the same diagnosis of my Gaomon M6 in #555 for your reference.

VID: "256c"
PID: "0064"
vendor: Gaomon
product: M6
Product page: [https://www.gaomon.cn/Pen_Tablet/M6.html](url)

[descriptors.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/7070694/descriptors.txt)
[hid_report_descriptors.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/7070695/hid_report_descriptors.txt)
[pen_buttons.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/7070696/pen_buttons.txt)
[pen_pressure.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/7070697/pen_pressure.txt)
[pen_tilt.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/7070698/pen_tilt.txt)
[pen_coords.txt](https://github.com/DIGImend/digimend-kernel-drivers/files/7070699/pen_coords.txt)

Unfortunately, there is no records of "tee frame_dials" & "tee frame_buttons", so these two files are unavailable. Btw, this did not bundle any mouse.
If you have any questions or comments, please let me know, thanks for your help.

**Comment by nguyentrongquocuet** [comment]
> Thanks for your information. After searching other issues, in #555, M6 seems workable partially. Meanwhile, I will follow to collect the diagnosis for developing later. Thanks a lot.

I glad you made it work, can you tell me what steps you've done to make it work. I've tried over 1 week and it still not work, all i got is just like 1/3 of drawing area can be used.
Apology my English.

**Comment by nukawa** [comment]
> > Thanks for your information. After searching other issues, in #555, M6 seems workable partially. Meanwhile, I will follow to collect the diagnosis for developing later. Thanks a lot.
> 
> I glad you made it work, can you tell me what steps you've done to make it work. I've tried over 1 week and it still not work, all i got is just like 1/3 of drawing area1/3 of drawing can be used. Apology my English.

Sorry, may I know about your environment? For me (Ubuntu 20.04 with digimend-kernel-drivers v10), it is still totally unworkable, is yours able to do 1/3 of drawing area partially already?

**Comment by nguyentrongquocuet** [comment]
> > > Thanks for your information. After searching other issues, in #555, M6 seems workable partially. Meanwhile, I will follow to collect the diagnosis for developing later. Thanks a lot.
> > 
> > 
> > I glad you made it work, can you tell me what steps you've done to make it work. I've tried over 1 week and it still not work, all i got is just like 1/3 of drawing area1/3 of drawing can be used. Apology my English.
> 
> Sorry, may I know about your environment? For me (Ubuntu 20.04 with digimend-kernel-drivers v10), it is still totally unworkable, is yours able to do 1/3 of drawing area partially already?

Im currently using EndeavourOS, which based on Arch linux. Im done creating `/etc/X11/..../50-tablet.conf`, reboot and it works. But only 1/3 tablet area works.

**Comment by nguyentrongquocuet** [comment]
I think when the tablet get plugged in, the tablet itself turns to Android mode, which uses 1/3 tablet area. I tried rotate screen for 90deg and that makes the drawing area fit the screen perfectly
![image](https://user-images.githubusercontent.com/55043222/150639806-2d39c1a1-f2f1-4bfb-95ad-55902c4bb8fe.png)

**Comment by nukawa** [comment]
Wow~For me, this seems good enough so far....
However, I am a brand new user of linux, my knowledge is limited.......I am just able to adopt the fundamental method, like installing with digimend-kernel-drivers v10. 
If available, would you mind sharing the basic information to set it step by step, such as a existing blog or website?? Thanks a lot.

**Comment by nguyentrongquocuet** [comment]
I followed [this Arch-linux wiki](https://wiki.archlinux.org/title/wacom_tablet#Non-Wacom_tablets)
I think u should try these steps:
* install `input-wacom`, it should be available via `apt-get`
* create `50-tablet.conf` in `/etc/X11/xorg.conf.d/`
* content of the file should be:
  ```Section "InputClass"
    Identifier "Tablet"
    Driver "wacom"
    MatchDevicePath "/dev/input/event*"
    MatchUSBID "256c:0064"
    EndSection
```
* reboot and it should work

**Comment by JoseExposito** [comment]
Hi!

Your issue should be fixed by [DIGImend v13](https://github.com/DIGImend/digimend-kernel-drivers/releases/tag/v13). Please, if you have a chance, give it a try and report any problems found.

Thanks!
