### ISSUE TITLE
dual screen

### ISSUE THREAD

**Issue by AleYepes823** [DIGImend/digimend-kernel-drivers#571]
Hi, how can i change the prestablished screen where the tablet works??? I have a laptop and an external monitor, the tablet is currently working on the built in screen but i would want it to work in the external monitor, any ideas on how to do it??

**Comment by polirritmico** [comment]
In KDE you could assign a shortcut for that on the tablet config screen.

**Comment by AleYepes823** [comment]
THANK YOU SO MUCH!!!
