### ISSUE TITLE
no detect huion W58 in Ubuntu 16.04

### ISSUE THREAD

**Issue by blackdrum** [DIGImend/digimend-kernel-drivers#58]
I bought a huion tablet w58, but when i try to use it, ubuntu 16.04 don't detect el driver, i installed the digimend v6 but i still can't use it
Regards

**Comment by spbnick** [comment]
Please send the output of `dmesg` after plugging in the tablet, output of `/sbin/modinfo hid-uclogic` , and also the output of `sudo evtest` and `xinput list` when tablet is plugged in.

**Comment by spbnick** [comment]
Also, the contents of /var/log/Xorg.0.log after plugging in the tablet would help.

**Comment by alexey-baranov** [comment]
@blackdrum any news?

**Comment by blackdrum** [comment]
Hello 
Now is working, the problem was my USB port, it was disable

Than you for your help
