### ISSUE TITLE
Gaomon 1060pro

### ISSUE THREAD

**Issue by PigeonAOA** [DIGImend/digimend-kernel-drivers#619]
I can't use this for Gaomon 1060pro.It didn't work.lsusb:256c:0064

**Comment by JoseExposito** [comment]
Hi!

Your issue should be fixed by [DIGImend v13](https://github.com/DIGImend/digimend-kernel-drivers/releases/tag/v13). Please, if you have a chance, give it a try and report any problems found.

Thanks!
