### ISSUE TITLE
Code correction in the file 'hid-uclogic-params.c'

### ISSUE THREAD

**Issue by pwrzec1** [DIGImend/digimend-kernel-drivers#658]
From the kernel 6.3, you must replace **hid_is_using_ll_driver(hdev, &usb_hid_driver)** with **hid_is_usb(hdev)**.

I did it as follows:

Code:
```
#if KERNEL_VERSION(4, 14, 0) <= LINUX_VERSION_CODE
|| !hid_is_using_ll_driver(hdev, &usb_hid_driver)
```

I changed to:
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 0)
|| !hid_is_usb(hdev)
#elif KERNEL_VERSION(4, 14, 0) <= LINUX_VERSION_CODE
|| !hid_is_using_ll_driver(hdev, &usb_hid_driver)
#endif
```

I tested this change on the HUION Kamvas 13 tablet. This solution works well on my computer. The computer configuration:
Distribution: openSUSE Tumbleweed, kernel 6.3.1, AMD Ryzen 7 3700, 64GB RAM. Plasma on X11.

**Comment by goodspeed34** [comment]
already fixed in https://github.com/DIGImend/digimend-kernel-drivers/commit/eca6e1b701bffb80a293234a485ebf6b4bc85562
