### ISSUE TITLE
Add support for the Huion H951P.

### ISSUE THREAD

**Issue by Demigirlboss** [DIGImend/digimend-kernel-drivers#676]
While the H950P is supported by DIGIMend, the H951P (which is only distinguished by its addition of a scroller, as far as I am aware) remains unsupported. I would like to request that support for this tablet officially be added to the kernel drivers.

**Comment by JoseExposito** [comment]
Hi!

Your issue should be fixed by [DIGImend v13](https://github.com/DIGImend/digimend-kernel-drivers/releases/tag/v13). Please, if you have a chance, give it a try and report any problems found.

Thanks!
