### ISSUE TITLE
H420 recognized but not responding

### ISSUE THREAD

**Issue by StrayLamb2** [DIGImend/digimend-kernel-drivers#69]
I work on Xubuntu 16.04 kernel 4.4.0.78, installed the .deb and everything was fine. A day passed, and now the tablet is not responding. Everything except xinput sees the tablet, but xinput refuses to recognize it... Any ideas? Tried to: reinstall driver, rmmod/modprob, kernel reinstall, plug/repug, start with unplugged device/start with plugged device.

**Comment by StrayLamb2** [comment]
by the way, I have to report that hid-huion seems to not be loaded, but the installation on my kernel was fine from dpkg...

**Comment by StrayLamb2** [comment]
not sure how and why, but running the software updater fixed it... :/

**Comment by spbnick** [comment]
`dmesg` output could have helped. Also, upgrade output. Perhaps the driver failed to build.

**Comment by StrayLamb2** [comment]
dmesg saw a huion device, so I guess it recognized it...

**Comment by spbnick** [comment]
Sure. The question is which driver handled it.

**Comment by StrayLamb2** [comment]
I think it was uc-logic, but it doesn't matter now that I can't reproduce it I guess... Anyways, as a contribution, so that this thread is not completely useless, if anyone can't get the drivers to work, try the software updates on settings after installing the .deb. :D
