### ISSUE TITLE
Huion Inspiroy 2 L spans both monitors (GNOME, Wayland)

### ISSUE THREAD

**Issue by Amberwq** [DIGImend/digimend-kernel-drivers#696]
Heya! Like the title says, at the moment my tablet spans both the primary and secondary monitors, which means I can only use a single half of my tablet. Every solution I've seen online was X11 specific, is there a Wayland solution to the problem?

**Comment by JoseExposito** [comment]
Hi!

You should be able to configure it in Settings > Wacom Tablet. For example, in GNOME:

![image](https://github.com/DIGImend/digimend-kernel-drivers/assets/1335948/f33c0aec-f94b-481f-8ced-75785f85cb32)

But your tablet needs to be included in libwacom first.

I think it is this one:
https://github.com/linuxwacom/libwacom/blob/master/data/huion-inspiroy-2-l---h1061p.tablet

But if I remember correctly it hasn't been released yet.

Meanwhile, you can add the required changes locally following:
https://github.com/linuxwacom/libwacom?tab=readme-ov-file#adding-tablet-descriptions-to-libwacom
