### ISSUE TITLE
Gimp and tablet huion H420

### ISSUE THREAD

**Issue by kendzi** [DIGImend/digimend-kernel-drivers#7]
I have problem trying to run tablet huion h420 and gimp. I'm not sure if it is problem with gimp or that driver. I [made post](http://gimpforums.com/thread-gimp-and-tablet-huion-h420) on gimp forum but no any answer yet. 

In short tablet is working inside Ubuntu, I can move mouse pointer. But it is impossible to use Gimp when tablet is connected. Simpy drawing area is not responding on mouse click or tablet clicks. Everything starts working as soon as I disconnect tablet. Inside gimp console output I get an error when starting  with connected tablet:

```
(gimp-2.8:5770): Gimp-Widgets-CRITICAL **: gimp_device_info_set_device: assertion '(info->device == NULL && GDK_IS_DEVICE (device)) || (GDK_IS_DEVICE (info->device) && device == NULL)' failed

(gimp-2.8:5770): Gimp-Widgets-CRITICAL **: gimp_device_info_set_device: assertion '(info->device == NULL && GDK_IS_DEVICE (device)) || (GDK_IS_DEVICE (info->device) && device == NULL)' failed
```

**Comment by spbnick** [comment]
@kendzi You can try the latest master which names device nodes differently. This might solve your GIMP problem.

**Comment by kendzi** [comment]
I managed to forget that I have tablet, but whatever...

I had installed master and something was changed, but I don't say that is working.
1. In menu > "Edit" > "Input Devices" I get four new entries regarding that crappy tablet. I attach screenshot. 
2. Only one entry named "HUION H42 Pen" is "working", by working I mean behave exactly like previously, it is working on Screen mode, but in Window mode there is the same offset between where cursor really is and where drawing is made.
3. Whats for are that not working entries in Input Device menu? 
4. As I have two big screens and tablet is extremely small and not to precise, it is completely useless in screen mode ... 

![screenshot from 2015-03-30 22 26 05](https://cloud.githubusercontent.com/assets/811830/6906122/0f899dfc-d72d-11e4-9b5a-0d91c7cd31e5.png)

**Comment by spbnick** [comment]
The extra entries are for reporting frame buttons and the very rare mouse for other models. These tablets are made in a way which makes hard to distinguish the models, so the drivers don't try and assume anything could be present on any model.

In your case only the "Pen" device should work. The current situation is better than before, where the device nodes were named the same.

You should pretty much always use the "Screen" mode. I assume the "Window" mode was made specifically to make it easier to stay within the canvas when using the tablet.

Regarding two big screens, you can fix that in various ways as described here:

http://digimend.github.io/support/howto/drivers/evdev/#dual-and-multimonitor-set-up

and, if you use the xf86-input-wacom driver, here:

http://linuxwacom.sourceforge.net/wiki/index.php/Wacom_Tablet_Set_Up#Dual_and_Multi-Monitor_Set_Up

**Comment by spbnick** [comment]
No communication from reporter, closing. Please reopen this or open a new issue if the problem persists.
