### ISSUE TITLE
 hid-rebind: /sbin/hid-rebind: line 55: modprobe: command not found

### ISSUE THREAD

**Issue by vince-br-549** [DIGImend/digimend-kernel-drivers#8]
Nick's scrpt can't seem to find modprobe in the default path.
in my copy I added /sbin/

**Comment by spbnick** [comment]
Thank you for the report, Vince. This is unexpected. /sbin/ should be in the root's PATH. Which distro are you using and how you were starting /sbin/hid-rebind?

**Comment by spbnick** [comment]
Unable to reproduce the issue, no response from reporter. Closing.
